version: "{build}"
environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "8"
cache:
  - "%LOCALAPPDATA%\\Yarn"
  - node_modules
init:
  - git config --global core.autocrlf true
install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install
test_script:
  - node --version && npm --version
  - npm run build
build: off
