version: "2"
checks:
  identical-code:
    exclude_patterns:
    - "**/*.test.js"
  similar-code:
    exclude_patterns:
    - "**/*.test.js"
plugins:
  eslint:
    enabled: true
  fixme:
    enabled: true
exclude_patterns:
- ".idea/"
- "dist/"
