dist: trusty
language: node_js
node_js:
  - "lts/*"
  - "node"
cache:
  yarn: true
  directories:
    - "node_modules"
    - "$HOME/.sonar/cache"
addons:
  sonarcloud:
    organization: "paulsmirnov-github"
    branches:
      - dev
before_install:
  - yarn global add greenkeeper-lockfile@1
before_script:
  - greenkeeper-lockfile-update
after_script:
  - greenkeeper-lockfile-upload
script:
  - npm run build
  - sonar-scanner
after_success:
  - npm run coveralls
  - npm run codecov
  - npm run codacy
