dist: trusty
language: node_js
node_js:
  - "lts/*"
  - "node"
cache:
  yarn: true
  directories:
    - "node_modules"
    - "$HOME/.sonar/cache"
addons:
  sonarcloud:
    organization: "paulsmirnov-github"
    branches:
      - dev
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.27.5
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn global add greenkeeper-lockfile@1
before_script:
  - greenkeeper-lockfile-update
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > /tmp/cc-test-reporter
  - chmod +x /tmp/cc-test-reporter
after_script:
  - greenkeeper-lockfile-upload
script:
  - git status
  - npm run ci
after_success:
  - sonar-scanner
  - npm run coveralls
  - npm run codecov
  - npm run codacy
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then /tmp/cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
deploy:
  - provider: npm
    skip_cleanup: true
    email: "$NPM_EMAIL"
    api_key: "$NPM_AUTH_TOKEN"
    tag: latest
    on:
      tags: true
      node: "node"
      condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$
